#!/usr/bin/env python3
"""
Build a standalone, double-clickable CPLAN dashboard.

Embeds the Parquet outputs and meta.json as base64 directly into the dashboard
HTML so the result runs from file:// with no local web server. A small fetch()
shim intercepts requests for the known data files and serves them from the
embedded buffers; the existing DuckDB-WASM load logic is left untouched.

Usage:
    python pipeline/build_standalone.py

Output:
    pipeline/output/cplan_dashboard_standalone.html
"""

import base64
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
SRC_HTML = SCRIPT_DIR / "dashboard" / "index-v3.html"
OUTPUT_DIR = SCRIPT_DIR / "output"
OUT_HTML = OUTPUT_DIR / "cplan_dashboard_standalone.html"

# Files to embed: (filename, required)
DATA_FILES = [
    ("communications.parquet", True),
    ("packs.parquet", False),
    ("meta.json", False),
]


def log(msg=""):
    print(msg)


def build_shim(embedded):
    """Return the <script> block that serves the embedded files via fetch()."""
    payload = ",\n".join(f'        {name!r}: "{b64}"' for name, b64 in embedded.items())
    return f"""<script>
    // === Standalone data embedding (auto-generated by build_standalone.py) ===
    window.__EMBEDDED_FILES__ = {{
{payload}
    }};
    (function () {{
        function b64ToBytes(b64) {{
            const bin = atob(b64);
            const bytes = new Uint8Array(bin.length);
            for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
            return bytes;
        }}
        const realFetch = window.fetch ? window.fetch.bind(window) : null;
        window.fetch = function (input, init) {{
            let url = (typeof input === 'string') ? input : (input && input.url) || '';
            // meta.json is requested cache-busted (?t=...) — match on the path only.
            const path = url.split('?')[0];
            for (const name in window.__EMBEDDED_FILES__) {{
                if (path.endsWith(name)) {{
                    const bytes = b64ToBytes(window.__EMBEDDED_FILES__[name]);
                    const type = name.endsWith('.json')
                        ? 'application/json'
                        : 'application/octet-stream';
                    return Promise.resolve(new Response(bytes, {{
                        status: 200,
                        headers: {{ 'Content-Type': type }}
                    }}));
                }}
            }}
            if (!realFetch) return Promise.reject(new Error('fetch unavailable for ' + url));
            return realFetch(input, init);
        }};
    }})();
    </script>
"""


def main():
    if not SRC_HTML.exists():
        log(f"ERROR: source dashboard not found: {SRC_HTML}")
        sys.exit(1)

    embedded = {}
    for name, required in DATA_FILES:
        path = OUTPUT_DIR / name
        if not path.exists():
            if required:
                log(f"ERROR: required data file missing: {path}")
                log("       Run 'python pipeline/process_cplan.py' first.")
                sys.exit(1)
            log(f"  Skipping optional file (not found): {name}")
            continue
        b64 = base64.b64encode(path.read_bytes()).decode("ascii")
        embedded[name] = b64
        log(f"  Embedded {name} ({path.stat().st_size:,} bytes -> {len(b64):,} b64 chars)")

    html = SRC_HTML.read_text(encoding="utf-8")
    if "<head>" not in html:
        log("ERROR: could not find <head> in source HTML")
        sys.exit(1)
    html = html.replace("<head>", "<head>\n" + build_shim(embedded), 1)

    OUT_HTML.parent.mkdir(parents=True, exist_ok=True)
    OUT_HTML.write_text(html, encoding="utf-8")

    size_kb = OUT_HTML.stat().st_size / 1024
    bar = "=" * 64
    log("\n" + bar)
    log("  STANDALONE DASHBOARD BUILT")
    log(bar)
    log(f"  Saved to : {OUT_HTML}")
    log(f"  Size     : {size_kb:,.0f} KB  |  embedded files: {len(embedded)}")
    log("  Open it  : double-click the file above — no web server needed.")
    log("  Note     : DuckDB-WASM and Chart.js still load from CDN (needs internet).")
    log(bar)
    sys.stdout.flush()


if __name__ == "__main__":
    main()
