#!/usr/bin/env python3
"""Build the planning studio as one standalone, read-only, offline HTML file.

The studio has no external dependencies and derives every page from a single
`GET /api/activities` payload, so making it run from a `file://` URL needs only
two things: the activities embedded as JSON, and a repository that answers from
that JSON instead of the network (`pipeline/studio/snapshot.js`).

    database ──► this script ──► pipeline/output/cplan_studio_standalone.html
                     ▲
    pipeline/studio/ ┘   (index.html and every asset it references)

Two decisions worth knowing before changing anything here:

* **The rows come from the database, never from the Parquet snapshot.**
  Activities created in the studio have no `legacy_sp_id` and never reach
  `communications.parquet`; a Parquet-fed export would silently omit exactly the
  rows the studio exists to produce. No database, no export — this script fails
  loudly rather than shipping a partial plan.

* **Assets are read from `pipeline/studio/` at build time and never copied.**
  The asset list is derived from `index.html` itself, so a new script tag there
  is picked up automatically and the standalone cannot drift into being a second
  implementation of the studio.

The change history is deliberately not embedded: it names who changed what and
when, and this file is made to be handed around. `loadHistory` in the studio
already renders an empty state when the call fails, and the snapshot repository
rejects it with a message that explains itself.

Usage:
    python -m pipeline.scripts.build_studio_standalone
    python -m pipeline.scripts.build_studio_standalone --out /tmp/plan.html
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from sqlalchemy import select
from sqlalchemy.orm import Session

from pipeline.api.app import Activity, ActivityRead, SyncRun, serialize_sync_run
from pipeline.api.database import create_cplan_engine
from pipeline.api.import_snapshot import resolve_database_url
from pipeline.api.setup_backend import default_settings_path

PIPELINE_DIR = Path(__file__).resolve().parent.parent  # pipeline/scripts/ -> pipeline/
STUDIO_DIR = PIPELINE_DIR / "studio"
DEFAULT_OUT = PIPELINE_DIR / "output" / "cplan_studio_standalone.html"

STYLESHEET_RE = re.compile(r'<link\s+rel="stylesheet"\s+href="([^"]+)"\s*/?>')
SCRIPT_RE = re.compile(r'<script\s+src="([^"]+)"\s*>\s*</script>')


def log(message: str = "") -> None:
    print(message)


def collect_snapshot(database_url) -> dict:
    """Read the activities and the latest sync run straight from the database.

    Serialization goes through `ActivityRead`, the same pydantic model
    `GET /api/activities` returns, and `serialize_sync_run`, the same function
    `GET /api/sync-runs/latest` uses. A second hand-written serializer here would
    drift the first time a field is added, and the failure would surface as a
    subtly wrong dashboard rather than an error.
    """
    engine = create_cplan_engine(database_url)
    try:
        with Session(engine) as session:
            activities = list(session.scalars(select(Activity).order_by(Activity.start_date, Activity.id)))
            items = [ActivityRead.model_validate(row).model_dump(mode="json") for row in activities]
            sync_run = serialize_sync_run(session.scalar(select(SyncRun).order_by(SyncRun.ran_at.desc())))
    finally:
        engine.dispose()
    return {
        "exported_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "items": items,
        "sync_run": sync_run,
    }


def payload_script(snapshot: dict) -> str:
    """The embedded payload, as a `<script>` block placed before every asset.

    `<` is escaped throughout: an activity name containing `</script>` would
    otherwise close the block early and break the page. JSON's own escapes make
    `\\u003c` an exactly equivalent document, so nothing about the data changes.
    """
    encoded = json.dumps(snapshot, ensure_ascii=False).replace("<", "\\u003c")
    return (
        "<script>\n"
        "    // === Read-only snapshot payload (generated by build_studio_standalone.py) ===\n"
        f"    window.__CPLAN_SNAPSHOT__ = {encoded};\n"
        "    </script>"
    )


def inline_assets(html: str, studio_dir: Path) -> tuple[str, list[str]]:
    """Replace every local `<link rel=stylesheet>` and `<script src>` with its content.

    Returns the rewritten HTML and the asset names in the order they were
    inlined. Absolute URLs are left untouched — there are none today, and
    silently swallowing one would hide a newly introduced external dependency
    that the offline guarantee depends on not existing.
    """
    inlined: list[str] = []

    def read_asset(name: str) -> str:
        path = studio_dir / name
        if not path.exists():
            raise FileNotFoundError(f"asset referenced by index.html is missing: {path}")
        inlined.append(name)
        return path.read_text(encoding="utf-8")

    def replace_stylesheet(match: re.Match[str]) -> str:
        href = match.group(1)
        if "://" in href or href.startswith("data:"):
            return match.group(0)
        return f"<style>\n{read_asset(href)}\n</style>"

    def replace_script(match: re.Match[str]) -> str:
        src = match.group(1)
        if "://" in src:
            return match.group(0)
        return f"<script>\n{read_asset(src)}\n</script>"

    html = STYLESHEET_RE.sub(replace_stylesheet, html)
    html = SCRIPT_RE.sub(replace_script, html)
    return html, inlined


def build(database_url, out_path: Path) -> Path:
    snapshot = collect_snapshot(database_url)
    log(f"  Read {len(snapshot['items']):,} activities from the database")

    source = STUDIO_DIR / "index.html"
    if not source.exists():
        raise FileNotFoundError(f"studio index.html not found: {source}")
    html, inlined = inline_assets(source.read_text(encoding="utf-8"), STUDIO_DIR)
    for name in inlined:
        log(f"  Inlined {name}")

    # Before the first inlined asset, so snapshot.js and app.js both see it.
    marker = "<style>" if "<style>" in html else "<script>"
    index = html.index(marker)
    html = html[:index] + payload_script(snapshot) + "\n  " + html[index:]

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(html, encoding="utf-8")
    return out_path


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--settings", type=Path, default=default_settings_path())
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    return parser


def main(argv: list[str] | None = None) -> None:
    args = build_parser().parse_args(argv)
    database_url = resolve_database_url(args.settings)
    out_path = build(database_url, args.out)

    size_kb = out_path.stat().st_size / 1024
    bar = "=" * 64
    log("\n" + bar)
    log("  STANDALONE STUDIO BUILT")
    log(bar)
    log(f"  Saved to : {out_path}")
    log(f"  Size     : {size_kb:,.0f} KB")
    log("  Open it  : double-click the file above — no web server, no internet.")
    log("  Contents : read-only. Everyone who receives this file receives the")
    log("             whole plan in cleartext, with no access control.")
    log(bar)
    sys.stdout.flush()


if __name__ == "__main__":
    main()
